expensedemo/config/routes.rb
Rails.application.routes.draw do
  resources :exp_entries
  get 'home/index'
  devise_for :users
  resources :home
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

expensedemo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

expensedemo/app/models/exp_entry.rb
class ExpEntry
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic
  field :title, type: String
  field :group, type: Integer
  field :billNo, type: String
  field :amount, type: Float
  field :BillDate, type: Date
  field :user_id, type: Integer
  belongs_to :user
end

expensedemo/app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :exp_entries

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  # field :is_admin, type: Boolean, default: false
  field :is_admin, type: String, default: false


  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  include Mongoid::Timestamps

  def will_save_change_to_email?
  end
end

expensedemo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

expensedemo/app/controllers/exp_entries_controller.rb
class ExpEntriesController < ApplicationController
  before_action :set_exp_entry, only: %i[ show edit update destroy ]
  # before_action :authenticate_user!, except[]
  before_action :authenticate_user!

  # GET /exp_entries or /exp_entries.json
  def index
    if current_user != nil
      if current_user.email == "hkpin2@gmail.com"
        @exp_entries = ExpEntry.all
      else
        @exp_entries = current_user.exp_entries
      end
    end
  end

  # GET /exp_entries/1 or /exp_entries/1.json
  def show
  end

  # GET /exp_entries/new
  def new
    @exp_entry = ExpEntry.new
  end

  # GET /exp_entries/1/edit
  def edit
  end

  # POST /exp_entries or /exp_entries.json
  def create
    @exp_entry = ExpEntry.new(exp_entry_params)

    respond_to do |format|
      if @exp_entry.save
        # PostMailer.approved(current_user.email).deliver_later
        format.html { redirect_to exp_entry_url(@exp_entry), notice: "Exp entry was successfully created." }
        format.json { render :show, status: :created, location: @exp_entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exp_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exp_entries/1 or /exp_entries/1.json
  def update
    respond_to do |format|
      if @exp_entry.update(exp_entry_params)
        PostMailer.approved(current_user.email).deliver
        format.html { redirect_to exp_entry_url(@exp_entry), notice: "Exp entry was successfully updated." }
        format.json { render :show, status: :ok, location: @exp_entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exp_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exp_entries/1 or /exp_entries/1.json
  def destroy
    @exp_entry.destroy

    respond_to do |format|
      format.html { redirect_to exp_entries_url, notice: "Exp entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exp_entry
      @exp_entry = ExpEntry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exp_entry_params
      params.require(:exp_entry).permit(:title, :group, :billNo, :amount, :BillDate, :user_id)
    end
end

expensedemo/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

expensedemo/app/helpers/application_helper.rb
module ApplicationHelper
end

expensedemo/app/helpers/exp_entries_helper.rb
module ExpEntriesHelper
end

expensedemo/app/helpers/home_helper.rb
module HomeHelper
end

expensedemo/app/views/exp_entries/_form.html.erb
<%= form_with(model: exp_entry, local: true) do |form| %>
  <% if exp_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exp_entry.errors.count, "error") %> prohibited this exp_entry from being saved:</h2>

      <ul>
        <% exp_entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%# <%= form.label :user_id %>
    <%= form.number_field :user_id, value:current_user.id, type: :hidden %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :group %>
    <%= form.number_field :group %>
  </div>

  <div class="field">
    <%= form.label :billNo %>
    <%= form.text_field :billNo %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :BillDate %>
    <%= form.date_select :BillDate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<%# <%= link_to 'Back', exp_entries_path %>

<% end %>

expensedemo/app/views/exp_entries/edit.html.erb
<h1>Editing Exp Entry</h1>

<%= render 'form', exp_entry: @exp_entry %>

<%= link_to 'Show', @exp_entry %> |
<%= link_to 'Back', exp_entries_path %>

expensedemo/app/views/exp_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exp Entries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Group</th>
      <th>Billno</th>
      <th>Amount</th>
      <th>Billdate</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exp_entries.each do |exp_entry| %>
      <tr>
        <td><%= exp_entry.title %></td>
        <td><%= exp_entry.group %></td>
        <td><%= exp_entry.billNo %></td>
        <td><%= exp_entry.amount %></td>
        <td><%= exp_entry.BillDate %></td>
        <td><%= exp_entry.user_id %></td>
        <td><%= link_to 'Show', exp_entry %></td>
        <td><%= link_to 'Edit', edit_exp_entry_path(exp_entry) %></td>
        <td><%= link_to 'Destroy', exp_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exp Entry', new_exp_entry_path %>

<%= link_to 'Back', 'home' %>

expensedemo/app/views/exp_entries/new.html.erb
<h1>New Exp Entry</h1>

<%= render 'form', exp_entry: @exp_entry %>

<%= link_to 'Back', exp_entries_path %>

expensedemo/app/views/exp_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @exp_entry.title %>
</p>

<p>
  <strong>Group:</strong>
  <%= @exp_entry.group %>
</p>

<p>
  <strong>Billno:</strong>
  <%= @exp_entry.billNo %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @exp_entry.amount %>
</p>

<p>
  <strong>Billdate:</strong>
  <%= @exp_entry.BillDate %>
</p>

<p>
  <strong>User:</strong>
  <%= @exp_entry.user_id %>
</p>

<%= link_to 'Edit', edit_exp_entry_path(@exp_entry) %> |
<%= link_to 'Back', exp_entries_path %>

expensedemo/app/views/home/index.html.erb
<h1>Expense Tracker Demo App</h1>

<br/><br/>
<br/><br/>
<% if user_signed_in?%>
    <%= link_to 'Your Expances', exp_entries_path  %>
    <br/><br/>
 
    <%= link_to 'sign out', destroy_user_session_path, method: :delete  %>


<% else %>
    <%= link_to 'sign in', new_user_session_path %>
   
    <%= link_to 'sign up', new_user_registration_path %>
<% end %>
 
<br/><br/>

<p>Himanshu </p>
 

expensedemo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expensedemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>